/*
 * This source file was generated by the Gradle 'init' task
 */

// File: com/papertradefx/MainApp.java

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import repository.DBManager;

import java.util.Arrays;

/**
 * MainApp is the entry point of the application.
 */
public class MainApp extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        DBManager.createTables();
        if (DBManager.isPriceHistoryEmpty()) {
            for (String ticker : Arrays.asList("TQQQ", "UPRO", "SOXL")) {
                try {
                    DBManager.batchInsertPriceHistory(DBManager.loadPriceHistoryFromCSV("data/" + ticker + ".csv"));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        Parent root = FXMLLoader.load(getClass().getResource("/fxml/DateSelection.fxml"));
        primaryStage.setTitle("Date Selection");
        primaryStage.setScene(new Scene(root));
        primaryStage.show();
    }

    /**
     * 테스트용 인사말을 반환합니다.
     */
    public String getGreeting() {
        return "Hello, PaperTradeFX!";
    }

    /**
     * Launches the application.
     * @param args command line args
     */
    public static void main(String[] args) {
        launch(args);
    }
}
